### ISSUE TITLE
Missing style field

### ISSUE THREAD

**Issue by GRosenberg** [vogellacompany/PreferencesSpy#6]
Eclipse 4.4.1 - Java 1.7

Installed normally, but produces an error when opening the view.  The view table is displayed, but without any of the Spy's button controls.

Seems that SWT FontData (in this version of Eclipse) does not have a style field, only getter and setter methods.

Actual error: 
Caused by: java.lang.NoSuchFieldError: style
at com.vogella.vde.preferencesspy.parts.PreferenceSpyPart.getBoldFontDescriptor(PreferenceSpyPart.java:110)
at com.vogella.vde.preferencesspy.parts.PreferenceSpyPart.postConstruct(PreferenceSpyPart.java:91)

**Comment by SimonScholz** [comment]
I just had a look at the JavaDoc and it says:
<pre>
the font style (Warning: This field is platform dependent)

IMPORTANT: This field is not part of the SWT public API. It is marked public only so that it can be shared within the packages provided by SWT. It is not available on all platforms and should never be accessed from application code.

@noreference
This field is not intended to be referenced by clients.
</pre>

Therefore I will deliver a patch for this issue. 

Thank you for reporting this bug.

**Comment by SimonScholz** [comment]
Resolved with commit I329dbb4cbbb9faeabbbf72cdfe4546352667d1e4.
Again thanks for reporting.
