### ISSUE TITLE
No icons and no preferences in the view..

### ISSUE THREAD

**Issue by opcoach** [vogellacompany/PreferencesSpy#7]
I installed the preference spy using the update site and when I open the view I get an empty view with no icons and no preferences inside... 

What should I do ?

Configuration :  eclipse Luna SR1, java 8, mac os X yosemite

![prefspyempty](https://cloud.githubusercontent.com/assets/1716878/5643145/e836aaba-9654-11e4-8d18-e30147d1b8a8.png)

**Comment by SimonScholz** [comment]
The problem here is that I also offered the PreferenceSpy as e4view in the plugin.xml, so that it is also shown in the "Show View Dialog", but as everything else like the toolbar is defined in a fragment.e4xmi this is not applied to the e4view reference in the plugin.xml.

I just removed the e4view from the plugin.xml and this results in the fact that the PreferenceSpy may only be opened by searching for it with the "Quick Access" (Ctrl + 3).

So you may update and use the "Quick Access" (Ctrl + 3), but it also works with the current version and the "Quick Access" (Ctrl + 3).

As an aside in Eclipse Mars we already resolved the "Show View Dialog" issue, so that in Mars the PreferenceSpy of the fragment.e4xmi will appear in this dialog.

Thank you for reporting this issue.

**Comment by opcoach** [comment]
Ok ! I works with the quick access ! 
Thanks
